name: PermSpawnpoint
version: 1.2
main: cc.vastsea.permspawnpoint.PermSpawnpoint
api-version: '1.20'
author: Snowball_233
description: A plugin that sets spawn points based on permission groups for first-time players
website: https://github.com/Snowball-233/PermSpawnpoint

depend:
  - Vault

commands:
  permspawn:
    description: Main command for PermSpawnpoint
    usage: /permspawn <reload|setspawn|list>
    permission: permspawnpoint.admin
    aliases: [ps, pspawn]

permissions:
  permspawnpoint.admin:
    description: Allows access to admin commands
    default: op
  permspawnpoint.bypass:
    description: Bypasses spawn point restrictions
    default: false